import Foundation

@main
struct OpenGrokVersionGenerator {
    static func main() throws {
        let arguments = Array(CommandLine.arguments.dropFirst())
        guard arguments.count == 3 || arguments.count == 4 else {
            throw GeneratorError.invalidArguments
        }

        let outputURL = URL(fileURLWithPath: arguments[0])
        let version = arguments[1]
        let releaseVersion = arguments[2].isEmpty ? nil : arguments[2]
        let shortCommit = arguments.count == 4 ? arguments[3] : nil
        guard !version.isEmpty else {
            throw GeneratorError.emptyVersion
        }

        let escapedVersion = version
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
        let escapedCommit = shortCommit?.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
        let escapedReleaseVersion = releaseVersion?.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
        let escapedReleaseLiteral = escapedReleaseVersion.map { "\"\($0)\"" } ?? "nil"
        let versionWithCommit = escapedCommit.map { "\(escapedVersion) (\($0))" } ?? escapedVersion

        let source = """
        // OpenGrokExecutableBuildStamp.generated.swift
        //
        // GENERATED FILE — do not edit by hand. Generated by the
        // OpenGrokVersionGenerator build executable.

        enum OpenGrokExecutableBuildStamp {
            static let releaseVersion: String? = \(escapedReleaseLiteral)
            static let versionWithCommit = "\(versionWithCommit)"
        }
        """

        try source.write(to: outputURL, atomically: true, encoding: .utf8)
    }
}

private enum GeneratorError: Error, CustomStringConvertible {
    case invalidArguments
    case emptyVersion

    var description: String {
        switch self {
        case .invalidArguments:
            return "usage: OpenGrokVersionGenerator <output-path> <display-version> <release-version-or-empty> [short-commit]"
        case .emptyVersion:
            return "version must not be empty"
        }
    }
}
