import Foundation

@main
struct OpenGrokVersionGenerator {
    static func main() throws {
        let arguments = Array(CommandLine.arguments.dropFirst())
        guard arguments.count == 2 || arguments.count == 3 else {
            throw GeneratorError.invalidArguments
        }

        let outputURL = URL(fileURLWithPath: arguments[0])
        let version = arguments[1]
        let shortCommit = arguments.count == 3 ? arguments[2] : nil
        guard !version.isEmpty else {
            throw GeneratorError.emptyVersion
        }

        let escapedVersion = version
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
        let escapedCommit = shortCommit?.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
        let escapedCommitLiteral = escapedCommit.map { "\"\($0)\"" } ?? "nil"

        let source = """
        // CompiledVersion.generated.swift
        //
        // GENERATED FILE — do not edit by hand. Generated by the
        // `OpenGrokVersionGenerator` build executable from the resolved
        // `GROK_VERSION` value at build time.

        import Foundation

        @usableFromInline
        internal enum OpenGrokCompiledVersion {
            /// The compile-time Open Grok version, injected from `GROK_VERSION`.
            @usableFromInline
            internal static let version: String = "\(escapedVersion)"

            @usableFromInline
            internal static let shortCommit: String? = \(escapedCommitLiteral)
        }
        """

        try source.write(to: outputURL, atomically: true, encoding: .utf8)
    }
}

private enum GeneratorError: Error, CustomStringConvertible {
    case invalidArguments
    case emptyVersion

    var description: String {
        switch self {
        case .invalidArguments:
            return "usage: OpenGrokVersionGenerator <output-path> <version>"
        case .emptyVersion:
            return "version must not be empty"
        }
    }
}
