import Testing

@testable import OpenGrokMermaid

/// Golden SVG documents for one diagram of each supported family.
///
/// Provenance: generated by this port, not copied from the Rust reference. The
/// vendored `mermaid-to-svg` crate ships no snapshot fixtures — its `*_tests.rs`
/// files and `samples/` assets were deliberately left out of the vendoring (see
/// the vendoring notes in third_party/mermaid-to-svg/Cargo.toml), so there is
/// nothing upstream to compare against byte for byte. These goldens therefore
/// pin *this* implementation's output: they catch unintended drift in geometry,
/// shape drawing, and document structure, and any deliberate change is meant to
/// be re-blessed by updating them here.
enum MermaidGoldens {
    static let minimalFlowchart = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg width="84" height="174" viewBox="0 0 84 174" xmlns="http://www.w3.org/2000/svg" style="background-color: #ffffff;">
        <rect x="0" y="0" width="84" height="174" fill="#ffffff" stroke="none"/>
        <defs>
          <marker id="arrowhead" markerWidth="8" markerHeight="8" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
          <marker id="arrowhead-thick" markerWidth="11" markerHeight="11" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
        </defs>
        <path d="M42.0,62.0L42.0,108.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <rect x="8.0" y="8.0" width="68.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="42.0" y="35.0">A</tspan>
        </text>
        <rect x="8.0" y="112.0" width="68.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="42.0" y="139.0">B</tspan>
        </text>
        </svg>

        """
    static let branchingFlowchart = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg width="299" height="435" viewBox="0 0 299 435" xmlns="http://www.w3.org/2000/svg" style="background-color: #ffffff;">
        <rect x="0" y="0" width="299" height="435" fill="#ffffff" stroke="none"/>
        <defs>
          <marker id="arrowhead" markerWidth="8" markerHeight="8" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
          <marker id="arrowhead-thick" markerWidth="11" markerHeight="11" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
        </defs>
        <path d="M157.8,47.0L157.8,93.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M134.4,175.7L125.7,186.1C117.0,196.5 99.5,217.2 90.7,234.0C82.0,250.8 82.0,263.7 82.0,270.1L82.0,276.5" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M181.1,175.7L189.8,186.1C198.5,196.5 216.0,217.2 224.8,233.4C233.5,249.5 233.5,261.0 233.5,266.8L233.5,272.5" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M82.0,334.5L82.0,384.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M261.0,291.7L261.0,291.7C261.0,291.7 261.0,291.7 266.0,289.0C271.0,286.3 281.0,280.9 286.0,275.5C291.0,270.2 291.0,264.9 291.0,257.0C291.0,249.0 291.0,238.4 291.0,227.8C291.0,217.1 291.0,206.5 291.0,198.5C291.0,190.6 291.0,185.3 277.3,180.0C263.6,174.6 236.2,169.2 221.1,166.1C206.0,162.9 203.3,162.1 201.9,161.7L200.5,161.2" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <polygon points="157.8,97.0 208.8,148.0 157.8,199.0 106.8,148.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="157.8" y="148.0">Ready?</tspan>
        </text>
        <circle cx="82.0" cy="407.5" r="19.5" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="82.0" y="407.5">End</tspan>
        </text>
        <rect x="125.4" y="8.0" width="64.8" height="39.0" rx="19.5" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="157.8" y="27.5">Begin</tspan>
        </text>
        <path d="M 206.0 283.4 L 206.0 331.6 A 27.5 6.9 0 0 0 261.0 331.6 L 261.0 283.4 A 27.5 6.9 0 0 0 206.0 283.4 Z" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <ellipse cx="233.5" cy="283.4" rx="27.5" ry="6.9" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="233.5" y="307.5">Queue</tspan>
        </text>
        <rect x="8.0" y="280.5" width="148.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="82.0" y="307.5">Do the work</tspan>
        </text>
        <rect x="68.0" y="224.0" width="28.0" height="28.0" fill="rgba(232,232,232,0.8)" rx="2"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="82.0" y="238.0">yes</tspan>
        </text>
        <rect x="223.5" y="224.0" width="20.0" height="28.0" fill="rgba(232,232,232,0.8)" rx="2"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="233.5" y="238.0">no</tspan>
        </text>
        </svg>

        """
    static let leftToRightFlowchart = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg width="485" height="144" viewBox="0 0 485 144" xmlns="http://www.w3.org/2000/svg" style="background-color: #ffffff;">
        <rect x="0" y="0" width="485" height="144" fill="#ffffff" stroke="none"/>
        <defs>
          <marker id="arrowhead" markerWidth="8" markerHeight="8" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
          <marker id="arrowhead-thick" markerWidth="11" markerHeight="11" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
        </defs>
        <path d="M108.0,72.0L197.8,72.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M302.2,52.5L311.0,48.3C319.8,44.2 337.4,35.8 351.1,31.7C364.8,27.5 374.7,27.5 379.6,27.5L384.5,27.5" fill="none" stroke="#333333" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead-thick)"/>
        <path d="M302.2,91.5L311.0,95.7C319.8,99.8 337.4,108.2 352.6,112.3C367.7,116.5 380.4,116.5 386.8,116.5L393.1,116.5" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="3 3" marker-end="url(#arrowhead)"/>
        <rect x="8.0" y="45.0" width="100.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="58.0" y="72.0">Input</tspan>
        </text>
        <polygon points="214.8,52.5 307.2,52.5 320.2,72.0 307.2,91.5 214.8,91.5 201.8,72.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="261.0" y="72.0">Validate</tspan>
        </text>
        <rect x="390.0" y="8.0" width="87.0" height="39.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <line x1="398.0" y1="8.0" x2="398.0" y2="47.0" stroke="#9370DB" stroke-width="1"/>
        <line x1="469.0" y1="8.0" x2="469.0" y2="47.0" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="433.5" y="27.5">Process</tspan>
        </text>
        <polygon points="416.6,97.0 469.9,97.0 469.9,136.0 416.6,136.0 397.1,116.5" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="438.4" y="116.5">Reject</tspan>
        </text>
        <rect x="133.0" y="58.0" width="44.0" height="28.0" fill="rgba(232,232,232,0.8)" rx="2"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="155.0" y="72.0">parse</tspan>
        </text>
        <rect x="345.0" y="13.5" width="20.0" height="28.0" fill="rgba(232,232,232,0.8)" rx="2"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="355.0" y="27.5">ok</tspan>
        </text>
        </svg>

        """
    static let clusteredFlowchart = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg width="219" height="486" viewBox="0 0 219 486" xmlns="http://www.w3.org/2000/svg" style="background-color: #ffffff;">
        <rect x="0" y="0" width="219" height="486" fill="#ffffff" stroke="none"/>
        <defs>
          <marker id="arrowhead" markerWidth="8" markerHeight="8" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
          <marker id="arrowhead-thick" markerWidth="11" markerHeight="11" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
        </defs>
        <rect x="55.0" y="8.0" width="156.0" height="198.0" fill="#ffffde" stroke="#aaaa33" stroke-width="1"/>
        <rect x="67.0" y="266.0" width="132.0" height="212.0" fill="#ffffde" stroke="#aaaa33" stroke-width="1"/>
        <path d="M133.0,94.0L133.0,140.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M133.0,352.0L133.0,398.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M133.0,198.0L133.0,294.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <rect x="63.0" y="144.0" width="140.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="133.0" y="171.0">Client API</tspan>
        </text>
        <path d="M 93.5 411.9 L 93.5 460.1 A 39.5 9.9 0 0 0 172.5 460.1 L 172.5 411.9 A 39.5 9.9 0 0 0 93.5 411.9 Z" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <ellipse cx="133.0" cy="411.9" rx="39.5" ry="9.9" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="133.0" y="436.0">Database</tspan>
        </text>
        <rect x="75.0" y="298.0" width="116.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="133.0" y="325.0">Service</tspan>
        </text>
        <rect x="75.0" y="40.0" width="116.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="133.0" y="67.0">Browser</tspan>
        </text>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="133.0" y="20.0">Front end</tspan>
        </text>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="133.0" y="278.0">Back end</tspan>
        </text>
        </svg>

        """
    static let cyclicFlowchart = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg width="114" height="278" viewBox="0 0 114 278" xmlns="http://www.w3.org/2000/svg" style="background-color: #ffffff;">
        <rect x="0" y="0" width="114" height="278" fill="#ffffff" stroke="none"/>
        <defs>
          <marker id="arrowhead" markerWidth="8" markerHeight="8" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
          <marker id="arrowhead-thick" markerWidth="11" markerHeight="11" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
        </defs>
        <path d="M42.0,62.0L42.0,108.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M42.0,166.0L42.0,212.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M76.0,222.4L76.0,222.4C76.0,222.4 76.0,222.4 81.0,218.9C86.0,215.3 96.0,208.3 101.0,201.3C106.0,194.3 106.0,187.5 106.0,177.1C106.0,166.7 106.0,152.9 106.0,139.0C106.0,125.1 106.0,111.3 106.0,100.9C106.0,90.5 106.0,83.7 101.0,76.7C96.0,69.7 86.0,62.7 81.0,59.1C76.0,55.6 76.0,55.6 76.0,55.6L76.0,55.6" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <rect x="8.0" y="8.0" width="68.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="42.0" y="35.0">A</tspan>
        </text>
        <rect x="8.0" y="112.0" width="68.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="42.0" y="139.0">B</tspan>
        </text>
        <rect x="8.0" y="216.0" width="68.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="42.0" y="243.0">C</tspan>
        </text>
        </svg>

        """
    static let minimalStateDiagram = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg width="114" height="302" viewBox="0 0 114 302" xmlns="http://www.w3.org/2000/svg" style="background-color: #ffffff;">
        <rect x="0" y="0" width="114" height="302" fill="#ffffff" stroke="none"/>
        <defs>
          <marker id="arrowhead" markerWidth="8" markerHeight="8" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
          <marker id="arrowhead-thick" markerWidth="11" markerHeight="11" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
        </defs>
        <path d="M34.5,22.0L34.5,68.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M34.5,112.0L34.5,186.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M60.9,198.3L60.9,198.3C60.9,198.3 60.9,198.3 65.9,196.3C70.9,194.3 80.9,190.3 85.9,186.3C90.9,182.4 90.9,178.5 90.9,172.6C90.9,166.7 90.9,158.9 90.9,151.0C90.9,143.1 90.9,135.3 90.9,129.4C90.9,123.5 90.9,119.6 84.2,115.7C77.6,111.7 64.2,107.7 57.5,105.7C50.9,103.7 50.9,103.7 50.9,103.7L50.9,103.7" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <path d="M34.5,230.0L34.5,276.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <rect x="18.1" y="72.0" width="32.8" height="40.0" rx="5.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="34.5" y="92.0">Idle</tspan>
        </text>
        <rect x="8.0" y="190.0" width="52.9" height="40.0" rx="5.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="34.5" y="210.0">Running</tspan>
        </text>
        <circle cx="34.5" cy="287.0" r="7.0" fill="#9370DB" stroke="#ffffff" stroke-width="1"/>
        <circle cx="34.5" cy="287.0" r="3.9" fill="#ffffff" stroke="none"/>
        <circle cx="34.5" cy="15.0" r="7.0" fill="#333333" stroke="#333333" stroke-width="1.5"/>
        <rect x="15.7" y="137.0" width="37.5" height="28.0" fill="rgba(232,232,232,0.8)" rx="2"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="34.5" y="151.0">start</tspan>
        </text>
        <rect x="75.5" y="132.3" width="30.8" height="28.0" fill="rgba(232,232,232,0.8)" rx="2"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="90.9" y="146.3">stop</tspan>
        </text>
        </svg>

        """
    static let styledFlowchart = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg width="116" height="174" viewBox="0 0 116 174" xmlns="http://www.w3.org/2000/svg" style="background-color: #ffffff;">
        <rect x="0" y="0" width="116" height="174" fill="#ffffff" stroke="none"/>
        <defs>
          <marker id="arrowhead" markerWidth="8" markerHeight="8" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
          <marker id="arrowhead-thick" markerWidth="11" markerHeight="11" refX="5" refY="5" orient="auto" markerUnits="userSpaceOnUse" viewBox="0 0 10 10">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#333333" stroke="#333333" stroke-width="1"/>
          </marker>
        </defs>
        <path d="M58.0,62.0L58.0,108.0" fill="none" stroke="#333333" stroke-width="1.0" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#arrowhead)"/>
        <rect x="8.0" y="8.0" width="100.0" height="54.0" rx="0.0" fill="#f9f" stroke="#333" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="58.0" y="35.0">Alpha</tspan>
        </text>
        <rect x="12.0" y="112.0" width="92.0" height="54.0" rx="0.0" fill="#ECECFF" stroke="#9370DB" stroke-width="1"/>
        <text text-anchor="middle" dominant-baseline="central" font-family="Trebuchet MS, verdana, arial, sans-serif" font-size="16" fill="#333333">
        <tspan x="58.0" y="139.0">Beta</tspan>
        </text>
        </svg>

        """
    static let all: [(name: String, svg: String)] = [
        ("minimalFlowchart", minimalFlowchart),
        ("branchingFlowchart", branchingFlowchart),
        ("leftToRightFlowchart", leftToRightFlowchart),
        ("clusteredFlowchart", clusteredFlowchart),
        ("cyclicFlowchart", cyclicFlowchart),
        ("minimalStateDiagram", minimalStateDiagram),
        ("styledFlowchart", styledFlowchart),
    ]
}

@Suite("Golden SVG")
struct MermaidGoldenTests {
    private func golden(_ name: String) -> String? {
        MermaidGoldens.all.first { $0.name == name }?.svg
    }

    @Test("each sample renders to its recorded document")
    func goldensMatch() throws {
        for sample in MermaidSamples.all {
            let expected = try #require(golden(sample.name), "no golden for \(sample.name)")
            let actual = try MermaidRenderer.render(sample.source)
            #expect(actual == expected, "\(sample.name) drifted from its golden")
        }
    }

    @Test("every supported family has a golden")
    func coverage() {
        #expect(MermaidGoldens.all.count == MermaidSamples.all.count)
        #expect(MermaidGoldens.all.contains { $0.name == "minimalStateDiagram" })
        #expect(MermaidGoldens.all.contains { $0.name == "clusteredFlowchart" })
    }
}
