// CompiledVersion.generated.swift
//
// GENERATED FILE — do not edit by hand. Regenerate with
// `Sources/OpenGrokVersion/regenerate-compiled-version.sh`.
//
// This file is the SwiftPM equivalent of the Rust crate's
// `option_env!("GROK_VERSION")` compile-time injection in
// `xai-grok-version/src/lib.rs`. The Rust build.rs emits
// `cargo:rerun-if-env-changed=GROK_VERSION` so cargo rebuilds when the env var
// changes; SwiftPM cannot run build scripts without a `Package.swift` edit
// (W0-S1-owned), so this file is regenerated by an explicit script that reads
// `GROK_VERSION` from the environment and writes the constant here.
//
// The regeneration script falls back to the `OPEN_GROK_VERSION` file at the
// package root (matching the Rust release script's `version_file`), then to
// the canonical Open Grok release string `0.1.220-open-grok.57`. Two clean
// builds with distinct `GROK_VERSION` values produce distinct
// `OpenGrokVersion.compiledVersion` values after regeneration.

import Foundation

@usableFromInline
internal enum OpenGrokCompiledVersion {
    /// The compile-time Open Grok version, injected from `GROK_VERSION` at
    /// generation time. Mirrors the Rust `VERSION` constant.
    @usableFromInline
    internal static let version: String = "0.1.220-open-grok.57"
    @usableFromInline
    internal static let shortCommit: String? = nil
}
