// OpenGrokVersion.swift
//
// Open Grok — Swift port of `xai-grok-version`.
//
// Installed Open Grok CLI version, lockstepped with shipping binaries. The
// compiled version is injected from the `GROK_VERSION` environment variable at
// build time via `CompiledVersion.generated.swift` (regenerated by
// `regenerate-compiled-version.sh`), mirroring the Rust crate's
// `option_env!("GROK_VERSION")` + `build.rs` rerun-if-env-changed directive.
// `GROK_TEST_VERSION` overrides at runtime for tests, matching the Rust
// `TEST_VERSION_ENV` behavior. `displayVersion` and `displayVersionWithCommit`
// format version strings with a channel label such as `" [stable]"` or `""`.

import Foundation

/// Errors thrown by Open Grok version parsing.
public enum OpenGrokVersionError: Error, Equatable, Sendable, CustomStringConvertible {
    case invalidSemVer(input: String, reason: String)

    public var description: String {
        switch self {
        case .invalidSemVer(let input, let reason):
            return "invalid semver '\(input)': \(reason)"
        }
    }
}

/// Canonical Open Grok version surface, porting `xai-grok-version`.
public enum OpenGrokVersion {

    /// Environment variable that overrides the version for tests, matching
    /// the Rust reference `TEST_VERSION_ENV`.
    public static let testVersionEnvironmentVariable = "GROK_TEST_VERSION"

    /// The build-time env var that, when set, overrides the compiled version
    /// string. The Rust crate reads this via `option_env!("GROK_VERSION")` at
    /// compile time; the Swift port regenerates
    /// `CompiledVersion.generated.swift` from this env var via
    /// `Sources/OpenGrokVersion/regenerate-compiled-version.sh` (the SwiftPM
    /// equivalent of `cargo:rerun-if-env-changed=GROK_VERSION`, since SwiftPM
    /// build-tool plugins require a `Package.swift` edit owned by W0-S1).
    public static let compileTimeVersionEnvironmentVariable = "GROK_VERSION"

    /// Compiled-in Open Grok version, injected from `GROK_VERSION` at build
    /// time via `CompiledVersion.generated.swift`. Mirrors the Rust `VERSION`
    /// constant (`option_env!("GROK_VERSION")` with fallback to
    /// `CARGO_PKG_VERSION`). The generated file is regenerated by
    /// `Sources/OpenGrokVersion/regenerate-compiled-version.sh`, which reads
    /// `GROK_VERSION` from the environment, falls back to the `OPEN_GROK_VERSION`
    /// file at the package root, then to the canonical Open Grok release
    /// string. Two clean builds with distinct `GROK_VERSION` values produce
    /// distinct `compiledVersion` values after regeneration.
    public static var compiledVersion: String {
        OpenGrokCompiledVersion.version
    }

    /// Resolve the installed version string: `GROK_TEST_VERSION` override first
    /// (trimmed), then the compiled version.
    ///
    /// Mirrors the Rust `installed()` exactly: the presence of
    /// `GROK_TEST_VERSION` (even an empty value) is the override condition;
    /// its trimmed value is returned. When `GROK_TEST_VERSION=` is set, the
    /// result is `""` and `installedSemVer()` throws, matching
    /// `std::env::var(TEST_VERSION_ENV).map(|v| v.trim().to_string())`.
    ///
    /// `environment` defaults to the live process environment but is injectable
    /// so tests are deterministic without mutating process-global state.
    public static func installed(
        environment: [String: String] = ProcessInfo.processInfo.environment
    ) -> String {
        if let override = environment[testVersionEnvironmentVariable] {
            return override.trimmingCharacters(in: .whitespacesAndNewlines)
        }
        return compiledVersion
    }

    /// Parse the installed version as a semver.
    public static func installedSemVer(
        environment: [String: String] = ProcessInfo.processInfo.environment
    ) throws -> SemVerVersion {
        try SemVerVersion.parse(installed(environment: environment))
    }

    /// Format the compiled version with a channel label for user-facing
    /// display.
    ///
    /// `channelLabel` is a pre-formatted suffix such as `" [alpha]"`,
    /// `" [stable]"`, or `""` (empty when no cached pointer is available).
    /// Obtain it from `OpenGrokUpdate.channelLabel()` once that slice lands.
    ///
    /// Example: `"0.2.5 [stable]"` or `"0.2.5 [alpha]"`.
    public static func displayVersion(channelLabel: String) -> String {
        "\(compiledVersion)\(channelLabel)"
    }

    /// Format a version-with-commit string with a channel label.
    ///
    /// Same semantics as `displayVersion(channelLabel:)` but for the full
    /// `"0.2.5 (abc1234)"` string.
    public static func displayVersionWithCommit(
        _ versionWithCommit: String,
        channelLabel: String
    ) -> String {
        "\(versionWithCommit)\(channelLabel)"
    }
}
