#!/usr/bin/env bash
#
# regenerate-compiled-version.sh
#
# Regenerate `CompiledVersion.generated.swift` from the `GROK_VERSION`
# environment variable, mirroring the Rust crate's
# `option_env!("GROK_VERSION")` compile-time injection (see
# `xai-grok-version/src/lib.rs` and `build.rs`).
#
# The Rust build.rs emits `cargo:rerun-if-env-changed=GROK_VERSION` so cargo
# rebuilds when the env var changes. SwiftPM cannot run build scripts without a
# `Package.swift` edit (W0-S1-owned), so this script is the explicit
# regeneration step. The release process (and any build that wants to stamp a
# specific version) must run this script before `swift build`.
#
# Resolution order (matches the Rust reference + the Open Grok release script):
#   1. `GROK_VERSION` environment variable, if set and non-empty.
#   2. The first line of `OPEN_GROK_VERSION` at the package root, if present.
#   3. The canonical Open Grok release string `0.1.220-open-grok.58`
#      (the Rust `CARGO_PKG_VERSION` fallback equivalent for Open Grok).
#
# Usage:
#   GROK_VERSION=1.2.3 Sources/OpenGrokVersion/regenerate-compiled-version.sh
#   Sources/OpenGrokVersion/regenerate-compiled-version.sh   # use OPEN_GROK_VERSION or default
#
# Exit status: 0 on success, non-zero on write failure.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
package_root="$(cd "${script_dir}/../.." && pwd)"
generated_file="${script_dir}/CompiledVersion.generated.swift"
version_file="${package_root}/OPEN_GROK_VERSION"
default_version="0.1.220-open-grok.58"
short_commit="${GROK_COMMIT:-}"

if [[ -n "${GROK_VERSION:-}" ]]; then
    version="${GROK_VERSION}"
elif [[ -f "${version_file}" ]]; then
    version="$(sed -n '1p' "${version_file}" | tr -d '\r')"
    if [[ -z "${version}" ]]; then
        version="${default_version}"
    fi
else
    version="${default_version}"
fi

# Validate the version is a non-empty string with no whitespace-only content.
if [[ -z "${version}" || "${version}" =~ ^[[:space:]]*$ ]]; then
    echo "Error: resolved version is empty or whitespace-only." >&2
    exit 1
fi

# Escape backslashes and double quotes for safe embedding in a Swift string
# literal. The version string is semver-shaped (digits, dots, dashes, plus,
# alphanumerics) so escaping is defensive rather than expected.
escaped_version="$(printf '%s' "${version}" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
escaped_commit="$(printf '%s' "${short_commit}" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"

cat > "${generated_file}" <<EOF
// CompiledVersion.generated.swift
//
// GENERATED FILE — do not edit by hand. Regenerate with
// \`Sources/OpenGrokVersion/regenerate-compiled-version.sh\`.
//
// This file is the SwiftPM equivalent of the Rust crate's
// \`option_env!("GROK_VERSION")\` compile-time injection in
// \`xai-grok-version/src/lib.rs\`. The Rust build.rs emits
// \`cargo:rerun-if-env-changed=GROK_VERSION\` so cargo rebuilds when the env var
// changes; SwiftPM cannot run build scripts without a \`Package.swift\` edit
// (W0-S1-owned), so this file is regenerated by an explicit script that reads
// \`GROK_VERSION\` from the environment and writes the constant here.
//
// The regeneration script falls back to the \`OPEN_GROK_VERSION\` file at the
// package root (matching the Rust release script's \`version_file\`), then to
// the canonical Open Grok release string \`0.1.220-open-grok.58\`. Two clean
// builds with distinct \`GROK_VERSION\` values produce distinct
// \`OpenGrokVersion.compiledVersion\` values after regeneration.

import Foundation

@usableFromInline
internal enum OpenGrokCompiledVersion {
    /// The compile-time Open Grok version, injected from \`GROK_VERSION\` at
    /// generation time. Mirrors the Rust \`VERSION\` constant.
    @usableFromInline
    internal static let version: String = "${escaped_version}"
    @usableFromInline
    internal static let shortCommit: String? = $([[ -n "${short_commit}" ]] && printf '"%s"' "${escaped_commit}" || printf 'nil')
}
EOF

echo "Regenerated ${generated_file} with version '${version}'"
