// OpenGrokVersionBuildPlugin.swift
//
// Build-tool plugin that generates `CompiledVersion.generated.swift` from
// the `GROK_VERSION` environment variable at build time — the SwiftPM
// equivalent of the Rust crate's `option_env!("GROK_VERSION")` compile-time
// injection and `cargo:rerun-if-env-changed=GROK_VERSION` directive.
//
// Resolution order (matches the Rust reference + the Open Grok release
// script):
//   1. `GROK_VERSION` environment variable, if set and non-empty.
//   2. The first line of `OPEN_GROK_VERSION` at the package root, if present.
//   3. The canonical Open Grok release string `0.1.220-open-grok.21`.
//
// The plugin runs during SwiftPM's build planning phase. It determines the
// version string and returns a `.buildCommand` that writes the Swift source
// file to the plugin work directory. SwiftPM compiles the generated file as
// part of the `OpenGrokVersion` target. A clean build always re-runs the
// plugin, so two clean builds with distinct `GROK_VERSION` values produce
// distinct `OpenGrokVersion.compiledVersion` values — the parity the
// integration acceptance requires.

import Foundation
import PackagePlugin

@main
struct OpenGrokVersionBuildPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let outputFile = context.pluginWorkDirectory.appending("CompiledVersion.generated.swift")

        // Resolve the version string (same resolution order as the Rust
        // crate and `regenerate-compiled-version.sh`).
        let env = ProcessInfo.processInfo.environment
        let defaultVersion = "0.1.220-open-grok.21"

        let version: String
        if let grokVersion = env["GROK_VERSION"], !grokVersion.isEmpty {
            version = grokVersion
        } else {
            let versionFilePath = context.package.directory
                .appending("OPEN_GROK_VERSION")
                .string
            if FileManager.default.fileExists(atPath: versionFilePath) {
                let content = (try? String(contentsOfFile: versionFilePath, encoding: .utf8))?
                    .components(separatedBy: "\n").first?
                    .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
                version = content.isEmpty ? defaultVersion : content
            } else {
                version = defaultVersion
            }
        }

        // Validate the version is non-empty.
        guard !version.isEmpty else {
            throw NSError(
                domain: "OpenGrokVersionBuildPlugin",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "Resolved version is empty"]
            )
        }

        // Escape backslashes and double quotes for safe embedding in a
        // Swift string literal.
        let escaped = version
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")

        // Generate the Swift source content. This mirrors the format
        // produced by `regenerate-compiled-version.sh` so the two paths
        // produce structurally identical output.
        let source = """
        // CompiledVersion.generated.swift
        //
        // GENERATED FILE — do not edit by hand. Generated by the
        // `OpenGrokVersionBuildPlugin` build-tool plugin from the
        // `GROK_VERSION` environment variable at build time.
        //
        // This file is the SwiftPM equivalent of the Rust crate's
        // `option_env!("GROK_VERSION")` compile-time injection in
        // `xai-grok-version/src/lib.rs`. The Rust build.rs emits
        // `cargo:rerun-if-env-changed=GROK_VERSION` so cargo rebuilds when
        // the env var changes; this plugin regenerates the file on every
        // clean build, achieving the same parity.
        //
        // Resolution order: `GROK_VERSION` env var → `OPEN_GROK_VERSION`
        // file at the package root → canonical default
        // `0.1.220-open-grok.21`.

        import Foundation

        @usableFromInline
        internal enum OpenGrokCompiledVersion {
            /// The compile-time Open Grok version, injected from
            /// `GROK_VERSION` at build time. Mirrors the Rust `VERSION`
            /// constant.
            @usableFromInline
            internal static let version: String = "\(escaped)"
        }
        """

        // Use a heredoc to write the file, avoiding shell-escaping issues.
        // The EOF marker is unique enough to never collide with the source.
        let script = "cat > \"\(outputFile.string)\" <<'OPENGROK_VERSION_BUILD_PLUGIN_EOF'\n\(source)\nOPENGROK_VERSION_BUILD_PLUGIN_EOF"

        return [
            .buildCommand(
                displayName: "Generate OpenGrokVersion from GROK_VERSION=\(version)",
                executable: Path("/bin/sh"),
                arguments: ["-c", script],
                inputFiles: [],
                outputFiles: [outputFile]
            )
        ]
    }
}
